FROM node:14.15.0-alpine

WORKDIR /usr/src/app

RUN apk add --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing \
  vips-dev fftw-dev gcc g++ make libc6-compat \
  --virtual builds-deps build-base python

COPY package.json .

RUN npm install

RUN npm i bcrypt sharp
RUN npm install pm2@latest -g

COPY . .

RUN npm run build

EXPOSE 3000


CMD ["pm2-runtime","start" ,"ecosystem.config.json"]
